name: digital_humanities
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.14.4 <4.0.0"

dependencies:
  dio: ^5.3.4
  photo_manager: ^2.8.1
  image_picker: ^1.0.4
  http_parser: ^4.0.0
  open_file: ^3.2.1
  permission_handler: ^11.0.1
  http: ^1.1.0
  circular_bottom_navigation: ^2.3.0
  camera: ^0.10.5+4
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  saver_gallery: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
